version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: nikolaik/python-nodejs:latest
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - '3333:3333'
        volumes:
            - .:/app
        environment:
            - DIRECTORY=server
            - COMMAND=npm run watch:dev
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: mariadb:10.3
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: scrapy
            MYSQL_USER: scrapy
            MYSQL_PASSWORD: scrapy
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
