version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: nikolaik/python-nodejs:latest
        container_name: app
        restart: unless-stopped
        tty: true
        ports:
            - '3333:3333'
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /app
        networks:
            - app-network
    db:
        image: mysql:5.7.29
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: scrapy
            MYSQL_USER: scrapy
            MYSQL_PASSWORD: scr(scr)
            MYSQL_ROOT_PASSWORD: r(oo)t
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
